### ISSUE TITLE
Not sure if bug, but having trouble uploading due to folders permissions?

### ISSUE THREAD

**Issue by thedonquixotic** [corvideon/InstantWP#60]
Hi Seamus, 

I had sent you an email earlier this week when I found this project asking some questions. And then stuff went wonky with my usb install, so I decided to try out the beta and so far I've been pretty impressed with the improvements!

One problem though. I can't upload any files via the admin panel. When I try to do so, it tells me that it was unable to transfer. I looked around online and this seems to be a problem with migrating websites to new hosts, and then having some kind of folder permissions issue? 

http://2surge.com/how-to-fix-the-uploaded-file-could-not-be-moved-to-wp-content-error-message/

I found this article but I wasn't quite sure how to do this stuff inside InstantWP. I'm a digital artist making his first website, so my CLI knowledge is a little sparse. 

I did get the SFTP drive working though, so I can very easily just copy and paste stuff into the drive folder, but unfortunately it doesn't show up in the WP Media Library for some reason. 

I'm going to take a crack at following that article, and see if I can fix stuff, but maybe this info might help you in your dev process, or maybe you have some advice. Anyway thanks!

**Comment by thedonquixotic** [comment]
Okay so I read through the article, and it looks like I need to enable permissions for iwp, since it seems only root currently has permissions for changing files, and from what I read I need to change the wp-content folder to be accessible from the FTP user, and I'm assuming that iwp is the ftp user?

That didn't work.  It didn't break anything but it didn't fix the issue. So I decided to open up the scripts folder in the default directory location of the SSH to see if anything useful there. I see a file called "reset-wp-permissions". I opened it up in Nano. It looks like it's changing the owner permissions to a user called "apache" which is maybe then the FTP user?

I tried running the script, but it doesn't seem to be doing anything or executing etc.... 

I'm pretty much at a loss what to try next.

**Comment by thedonquixotic** [comment]
Oh! It's working! I guess the scripts worked! Woohoooo! 

I don't know if you don't want this cluttering up your issues git section, but it might be useful for future people who run into similar problems. 

Also I might be interested in helping out with this project? Like I said, I'm primarily a digital artist/designer, who is building his first WP website (after years of building static ones in HTML, CSS, and JS), so a lot of this stuff is new to me, but I might be able to contribute to the project through visual/marketing design etc. Anyway woo!

**Comment by thedonquixotic** [comment]
Ooof running a CSS preprocessor on the mounted drive is very very slow. I've got it working now but running the proprocessor in the root of the USB drive and then syncing it to the mounted drive, but it's not pretty. 

It also means giving up some of the truly "self contained" nature of the InstantWP dev environment. Means I have to have SFTP netdrive and Goodsync installed on whatever computer I stick the usb in. I wonder if there's a way to implement this through CLI that integrates a more self contained solution.

**Comment by corvideon** [comment]
Thanks for all the rich feedback there David - sorry I missed the beginning of the issue!
I will add all this feedback to the FAQ for future reference.
The permissions stuff can be tricky.
The way forward with the CSS preprocessor could be fixed by the following
- Install the tools you need on IWPServer using the Alpine apk command and call them from an SSH session. This makes the environment more self contained. You can also install Git so that you can save your work away from the VM.
-Try opening a command line to the mounted SFTP netdrive - just browse to the drive letter using cmd.exe. That will give you access to the files.
- You could also try mounting the webdav server that runs at http://iwp:iwp@127.0.0.1:10080/webdav/iwpserver.php - this can be mounted natively on some Windows versions (it breaks according to what you updates have installed - can be tricky)
- Use the portable version of WinSCP to do the syncing. It is really great.

Unfortunately the portable nature of IWP means some compromises but hopefully not too many.
